// installer.cpp — the new-sli deployer (single self-contained exe).
//
// WHAT THE USER SEES: a small window with a folder picker, an Install
// button and a live log. It writes the deployables (dxgi.dll, nvngx.dll,
// sli_engine.exe, sli_panel.exe, sli_ctl.exe and the default sli.ini)
// into the chosen game folder, writes an uninstaller
// (uninstall_sli.exe), and copies the vendor NR runtime when it
// travels beside the installer.
//
// ZERO TRACE: no admin rights, no registry, no services, no remembered
// state. Everything lands in ONE folder the user picked; uninstall
// deletes exactly the files the manifest lists (never anything it did
// not deploy) and then removes itself — after a full install/uninstall
// cycle nothing of new-sli remains on the system.
//
// The payload is embedded via the generated resource file (build/
// installer_payload.rc) except the ~165 MB vendor runtime, which is
// user-provided by design (licensing) and is copied from beside the
// installer when present.
//
// UNINSTALL: uninstall_sli.exe is a copy of this exe relaunched with
// --uninstall; the manifest written at install time drives the removal.

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <shlobj.h>

#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
#ifdef INSTALLER_CONSOLE
#include <iostream>
#endif

// payload: embedded RCDATA resources (installer_payload.rc, generated by
// CMake) — resolved at startup by LoadPayload()

namespace {

struct Blob { const wchar_t* name; HGLOBAL data; unsigned long len; };

// resolved at startup from the embedded RCDATA resources
Blob kBlobs[6];
int kBlobCount = 0;

bool LoadPayload()
{
    // numeric resource ids 1..6 in RCDATA (see MakeInstallerPayload.cmake);
    // MAKEINTRESOURCE, not L"1" — a string id looks up a resource NAMED
    // "1", which is not the same as numeric id 1
    const wchar_t* names[] = { L"dxgi.dll", L"nvngx.dll", L"sli_engine.exe",
                               L"sli_panel.exe", L"sli_ctl.exe", L"sli.ini" };
    for (int i = 0; i < 6; ++i)
    {
        const HRSRC r = FindResourceW(nullptr, MAKEINTRESOURCEW(i + 1),
                                      (LPCWSTR) RT_RCDATA);
        if (r == nullptr) return false;
        const HGLOBAL g = LoadResource(nullptr, r);
        if (g == nullptr) return false;
        const LPVOID p = LockResource(g);
        if (p == nullptr) return false;
        kBlobs[kBlobCount].name = names[i];
        kBlobs[kBlobCount].data = g;
        kBlobs[kBlobCount].len = SizeofResource(nullptr, r);
        ++kBlobCount;
    }
    return true;
}

// the vendor NR runtime: user-provided, copied from beside the installer
const wchar_t* kVendor[] = { L"nvngx_dlssnr.dll", L"nvngx.dll_dlssnr.dll" };

HWND gwnd = nullptr, glog = nullptr, gdir = nullptr, gbtn = nullptr;
bool gNoPopups = false;   // console/smoke mode: popups would block

void Popup(HWND owner, const wchar_t* text, const wchar_t* title, UINT kind)
{
    if (gNoPopups) return;
    MessageBoxW(owner, text, title, kind);
}

void Log(const char* fmt, ...)
{
    char buf[512];
    va_list ap; va_start(ap, fmt);
    _vsnprintf_s(buf, sizeof(buf), _TRUNCATE, fmt, ap);
    va_end(ap);
#ifdef INSTALLER_CONSOLE
    printf("%s\n", buf);   // console twin: smoke output goes to stdout
#else
    if (glog != nullptr)
    {
        SendMessageA(glog, LB_ADDSTRING, 0, (LPARAM) buf);
        const int n = (int) SendMessageA(glog, LB_GETCOUNT, 0, 0);
        if (n > 0) SendMessageA(glog, LB_SETTOPINDEX, n - 1, 0);
    }
#endif
}

bool WriteAllBytes(const std::wstring& path, const void* data, size_t len)
{
    HANDLE h = CreateFileW(path.c_str(), GENERIC_WRITE, 0, nullptr,
                           CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (h == INVALID_HANDLE_VALUE) return false;
    DWORD wr = 0;
    const BOOL ok = len == 0 ||
        (WriteFile(h, data, (DWORD) len, &wr, nullptr) && wr == len);
    CloseHandle(h);
    return ok != FALSE;
}

std::wstring ExeDir()
{
    wchar_t buf[MAX_PATH] = {};
    GetModuleFileNameW(nullptr, buf, MAX_PATH);
    std::wstring p = buf;
    const size_t k = p.find_last_of(L"\\/");
    return k == std::wstring::npos ? L"." : p.substr(0, k);
}

bool FileExists(const std::wstring& p)
{
    const DWORD a = GetFileAttributesW(p.c_str());
    return a != INVALID_FILE_ATTRIBUTES && !(a & FILE_ATTRIBUTE_DIRECTORY);
}

// ---------------------------------------------------------------------------
// ZERO TRACE by design: no registry writes, no system folders, no
// remembered state outside the target folder. Everything the installer
// touches lives in the ONE folder the user picked, and uninstall removes
// exactly that (the manifest lists every deployed file).
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// manifest: exactly what we deployed (uninstall deletes ONLY this)
// ---------------------------------------------------------------------------
std::wstring ManifestPath(const std::wstring& dir)
{
    return dir + L"\\sli_installed_files.txt";
}

int DoInstall(const std::wstring& dir)
{
    std::vector<std::wstring> installed;

    // the target folder must exist (the picker normally guarantees it;
    // headless/smoke runs may pass a fresh path)
    CreateDirectoryW(dir.c_str(), nullptr);

    for (int bi = 0; bi < kBlobCount; ++bi)
    {
        const Blob& b = kBlobs[bi];
        const std::wstring dst = dir + L"\\" + b.name;
        // never clobber a user's tuned ini silently
        if (wcscmp(b.name, L"sli.ini") == 0 && FileExists(dst))
        {
            Log("sli.ini already present - keeping the existing one");
            continue;
        }
        if (!WriteAllBytes(dst, b.data, b.len))
        {
            Log("FAILED to write %ls (folder writable? game closed?)", b.name);
            return 1;
        }
        Log("installed %ls (%lu KB)", b.name, b.len / 1024);
        installed.push_back(b.name);
    }

    // vendor NR runtime: copied only when it travels beside the installer
    for (const wchar_t* v : kVendor)
    {
        const std::wstring src = ExeDir() + L"\\" + v;
        if (!FileExists(src)) continue;
        const std::wstring dst = dir + L"\\" + v;
        if (!CopyFileW(src.c_str(), dst.c_str(), FALSE))
        {
            Log("FAILED to copy %ls (in use? close the game)", v);
            return 1;
        }
        Log("installed %ls (vendor NR runtime, user-provided)", v);
        installed.push_back(v);
    }

    // the uninstaller: a copy of this exe, relaunched with --uninstall
    wchar_t self[MAX_PATH] = {};
    GetModuleFileNameW(nullptr, self, MAX_PATH);
    const std::wstring uni = dir + L"\\uninstall_sli.exe";
    if (!CopyFileW(self, uni.c_str(), FALSE))
    {
        Log("FAILED to write the uninstaller (folder writable?)");
        return 1;
    }
    installed.push_back(L"uninstall_sli.exe");

    // manifest + ARP entry
    std::string m;
    for (const auto& f : installed)
    {
        char a[MAX_PATH] = {};
        WideCharToMultiByte(CP_UTF8, 0, f.c_str(), -1, a, sizeof(a),
                            nullptr, nullptr);
        m += a; m += "\n";
    }
    WriteAllBytes(ManifestPath(dir), m.c_str(), m.size());

    Log("");
    Log("DONE. The deployables live next to the game's exe.");
    Log("Launch the game, then sli_panel.exe. F6 panel / F7 offload A/B.");
    Popup(gwnd, L"new-sli installed.\n\nLaunch the game, then "
          L"sli_panel.exe.\nF6 opens the panel; F7 toggles the "
          L"offload A/B.", L"new-sli", MB_OK | MB_ICONINFORMATION);
    return 0;
}

int DoUninstall(const std::wstring& dir)
{
    HANDLE h = CreateFileW(ManifestPath(dir).c_str(), GENERIC_READ,
                           FILE_SHARE_READ, nullptr, OPEN_EXISTING, 0, nullptr);
    if (h == INVALID_HANDLE_VALUE)
    {
        if (!gNoPopups)
            MessageBoxW(nullptr, L"No install manifest found - nothing to do.",
                        L"new-sli uninstall", MB_OK | MB_ICONERROR);
        else
            printf("uninstall: no manifest found\n");
        return 1;
    }
    std::string m;
    char buf[4096]; DWORD r = 0;
    while (ReadFile(h, buf, sizeof(buf), &r, nullptr) && r > 0)
        m.append(buf, r);
    CloseHandle(h);

    int removed = 0, failed = 0;
    size_t k = 0;
    while (k < m.size())
    {
        size_t e = m.find('\n', k);
        if (e == std::string::npos) e = m.size();
        std::string line = m.substr(k, e - k);
        k = e + 1;
        while (!line.empty() && (line.back() == '\r' || line.back() == ' '))
            line.pop_back();
        if (line.empty()) continue;
        wchar_t w[MAX_PATH] = {};
        MultiByteToWideChar(CP_UTF8, 0, line.c_str(), -1, w, MAX_PATH);
        if (DeleteFileW((dir + L"\\" + w).c_str()))
            ++removed;
        else if (FileExists(dir + L"\\" + w))
            ++failed;   // in use — report, count as failure
        // already-gone files (previous partial uninstall) are fine
    }
    DeleteFileW(ManifestPath(dir).c_str());
    char msg[256];
    _snprintf_s(msg, sizeof(msg), _TRUNCATE,
                "Removed %d file(s).%s", removed,
                failed ? "\nSome files were in use - close the game and "
                         "panel, then run again." : "");
    if (!gNoPopups)
        MessageBoxA(nullptr, msg, "new-sli uninstall",
                    MB_OK | (failed ? MB_ICONWARNING : MB_ICONINFORMATION));
    else
        printf("uninstall: %s\n", msg);
    // ZERO TRACE: the uninstaller removes ITSELF last. A running exe
    // cannot delete its own file directly, so it relaunches cmd with a
    // one-liner that waits for this process to exit and then deletes it.
    // (Only the DEPLOYED copy — the smoke gate runs install+uninstall
    // from the build-tree exe and must survive its own test.)
    if (failed == 0)
    {
        wchar_t self[MAX_PATH] = {};
        GetModuleFileNameW(nullptr, self, MAX_PATH);
        const wchar_t* base = wcsrchr(self, L'\\');
        base = base ? base + 1 : self;
        if (wcscmp(base, L"uninstall_sli.exe") == 0)
        {
        wchar_t cmd[MAX_PATH + 64] = {};
        _snwprintf_s(cmd, _countof(cmd), _TRUNCATE,
                     L"/c timeout /t 2 /nobreak >nul & del \"%s\"", self);
        STARTUPINFOW si = { sizeof(si) };
        si.dwFlags = STARTF_USESHOWWINDOW;
        si.wShowWindow = SW_HIDE;
        PROCESS_INFORMATION pi = {};
        if (CreateProcessW(L"C:\\Windows\\System32\\cmd.exe", cmd,
                           nullptr, nullptr, FALSE, CREATE_NO_WINDOW,
                           nullptr, dir.c_str(), &si, &pi))
        {
            CloseHandle(pi.hProcess);
            CloseHandle(pi.hThread);
        }
        }
    }
    return failed ? 1 : 0;
}

// ---------------------------------------------------------------------------
// tiny Win32 UI: [label][folder edit][Browse][Install] + log listbox
// ---------------------------------------------------------------------------
void PickFolder(HWND owner)
{
    BROWSEINFOW bi = {};
    bi.hwndOwner = owner;
    bi.lpszTitle = L"Pick the game's folder (where the game's exe lives)";
    bi.ulFlags = BIF_RETURNONLYFSDIRS | BIF_USENEWUI;
    PIDLIST_ABSOLUTE pidl = SHBrowseForFolderW(&bi);
    if (pidl == nullptr) return;
    wchar_t path[MAX_PATH] = {};
    SHGetPathFromIDListW(pidl, path);
    CoTaskMemFree(pidl);
    if (path[0]) SetWindowTextW(gdir, path);
}

LRESULT CALLBACK WndProc(HWND h, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg)
    {
    case WM_COMMAND:
        if (LOWORD(wp) == 1002) PickFolder(h);
        else if (LOWORD(wp) == 1003)
        {
            wchar_t dir[MAX_PATH] = {};
            GetWindowTextW(gdir, dir, MAX_PATH);
            if (!dir[0])
            {
                MessageBoxW(h, L"Pick a folder first.", L"new-sli",
                            MB_OK | MB_ICONWARNING);
                break;
            }
            const DWORD a = GetFileAttributesW(dir);
            if (a == INVALID_FILE_ATTRIBUTES ||
                !(a & FILE_ATTRIBUTE_DIRECTORY))
            {
                MessageBoxW(h, L"That folder does not exist.", L"new-sli",
                            MB_OK | MB_ICONWARNING);
                break;
            }
            EnableWindow(gbtn, FALSE);
            if (DoInstall(dir) == 0)
                SetWindowTextW(gbtn, L"Installed");
            else
                EnableWindow(gbtn, TRUE);
        }
        break;
    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(h, msg, wp, lp);
}

} // namespace

int WINAPI wWinMain(HINSTANCE inst, HINSTANCE, PWSTR cmdLine, int)
{
    if (cmdLine && wcsstr(cmdLine, L"--uninstall"))
        return DoUninstall(ExeDir());   // the copy lives IN the target dir

    if (!LoadPayload())
    {
#ifdef INSTALLER_CONSOLE
        fprintf(stderr, "payload missing (build error)\n");
#else
        MessageBoxW(nullptr, L"Installer payload missing (build error).",
                    L"new-sli", MB_OK | MB_ICONERROR);
#endif
        return 1;
    }

    // --smoke <dir>: headless install + uninstall gate (CI / verification).
    // Console build only (INSTALLER_CONSOLE): the GUI build has no stdout.
#ifdef INSTALLER_CONSOLE
    if (cmdLine && wcsstr(cmdLine, L"--smoke"))
    {
        wchar_t dir[MAX_PATH] = {};
        wchar_t* k = wcsstr(cmdLine, L"--smoke") + wcslen(L"--smoke");
        while (*k == L' ') ++k;
        wchar_t* end = k;
        while (*end && *end != L' ') ++end;
        *end = 0;
        wcscpy_s(dir, k);
        if (!dir[0])
        {
            printf("usage: sli_installer --smoke <dir>\n");
            return 1;
        }
        // a hidden window so Log() has somewhere to send its lines
        glog = CreateWindowW(L"STATIC", nullptr, WS_OVERLAPPED, 0, 0, 0, 0,
                             nullptr, nullptr, inst, nullptr);
        printf("smoke: installing into %ls\n", dir);
        // (MessageBox popups would block the gate — neuter them)
        gNoPopups = true;
        if (DoInstall(dir) != 0) { printf("smoke: INSTALL FAILED\n"); return 1; }
        if (DoUninstall(dir) != 0) { printf("smoke: UNINSTALL FAILED\n"); return 1; }
        printf("smoke: PASS\n");
        return 0;
    }
#endif

    CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);

    WNDCLASSW wc = {};
    wc.lpfnWndProc = WndProc;
    wc.hInstance = inst;
    wc.hCursor = LoadCursorW(nullptr, (LPCWSTR) IDC_ARROW);
    wc.hbrBackground = (HBRUSH) (COLOR_WINDOW + 1);
    wc.lpszClassName = L"new-sli-installer";
    RegisterClassW(&wc);

    gwnd = CreateWindowW(wc.lpszClassName, L"new-sli installer",
                         WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU |
                         WS_MINIMIZEBOX, CW_USEDEFAULT, CW_USEDEFAULT,
                         600, 430, nullptr, nullptr, inst, nullptr);

    CreateWindowW(L"STATIC",
                  L"Install folder (the game's folder, next to its exe):",
                  WS_CHILD | WS_VISIBLE, 16, 14, 440, 18, gwnd, nullptr,
                  inst, nullptr);
    gdir = CreateWindowW(L"EDIT", L"", WS_CHILD | WS_VISIBLE | WS_TABSTOP |
                         ES_AUTOHSCROLL, 16, 38, 440, 24, gwnd,
                         (HMENU) (INT_PTR) 1001, inst, nullptr);
    CreateWindowW(L"BUTTON", L"Browse...", WS_CHILD | WS_VISIBLE | WS_TABSTOP,
                  470, 36, 90, 26, gwnd, (HMENU) (INT_PTR) 1002, inst, nullptr);
    gbtn = CreateWindowW(L"BUTTON", L"Install", WS_CHILD | WS_VISIBLE |
                         WS_TABSTOP | BS_DEFPUSHBUTTON, 470, 68, 90, 30,
                         gwnd, (HMENU) (INT_PTR) 1003, inst, nullptr);
    glog = CreateWindowW(L"LISTBOX", nullptr, WS_CHILD | WS_VISIBLE |
                         LBS_NOINTEGRALHEIGHT | WS_VSCROLL, 16, 110, 544,
                         260, gwnd, nullptr, inst, nullptr);

    // (zero-trace: no last-folder memory is read or written)

    ShowWindow(gwnd, SW_SHOW);
    MSG msg;
    while (GetMessageW(&msg, nullptr, 0, 0) > 0)
    {
        if (!IsDialogMessageW(gwnd, &msg))
        {
            TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }
    }

    CoUninitialize();
    return 0;
}
